services:
  app_auth:
    container_name: app_auth
    build:
      context: ./admin
    ports:
      - "8095:8095"
    depends_on:
      bd_auth:
        condition: service_healthy

  bd_auth:
    container_name: bd_auth
    image: postgres:latest
    restart: always
    ports:
      - "5433:5433"
    env_file:
      - .env
    command: postgres -p 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5433"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    volumes:
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json
    env_file:
      - .env

volumes:
  pgdata:
